name: dart_container
description: Injection container and app server for Dart. Provides functionality similar to Java's Spring dependency injection and appserver, with scheduled tasks support and conditional callbacks for container objects.
version: 1.0.6
repository: https://github.com/ctrohin/dart_container.git

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dart_router_extended: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
